# Generated by Django 5.0.2 on 2024-02-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_delete_li_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='category_id',
            new_name='is_deleted',
        ),
    ]
