# Generated by Django 5.0.2 on 2024-02-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_rename_category_id_task_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
